// gen-skill.ts — the reference files of the Claude skill (.claude/skills/pracdraw/reference/). Run: npm run gen:skill
// They are written from the symbol code (anchors, parameters, cavities), spec/catalogue.json, spec/templates.json and the
// presets, so that they cannot drift from what the editor draws. A unit test (src/skill.test.ts, "skill-reference-is-current")
// fails when a file differs from what this script would write now. SKILL.md is written by hand and is not touched.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { PACKS } from '../src/editor/search.ts'
import { PRESETS } from '../src/model/contents.ts'
import { RECIPE_PRESETS } from '../src/model/recipe.ts'
import { SYMBOLS, geometry, labelText } from '../src/symbols/registry.ts'
import type { ParamDef, SymbolDef } from '../src/symbols/types.ts'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
/** The skill folder, at the root of the repository. */
export const SKILL_DIR = resolve(ROOT, '..', '.claude', 'skills', 'pracdraw')

interface Row {
  id: string
  name: string
  pack: string
}
interface Plan {
  id: string
  title: string
  group: string
  refs: string
  uses: string[]
  notes: string
}

const json = <T>(file: string): T => JSON.parse(readFileSync(join(ROOT, 'spec', file), 'utf8')) as T

const HEADER = (what: string): string => `<!-- Generated by \`npm run gen:skill\` from ${what}. Do not edit: change the source and run it again. -->\n`

/** A table cell: no pipes, no line breaks. */
const cell = (s: string): string => s.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ')
const table = (head: string[], rows: string[][]): string =>
  [`| ${head.join(' | ')} |`, `| ${head.map(() => '---').join(' | ')} |`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n')

function paramText(p: ParamDef): string {
  switch (p.type) {
    case 'boolean':
      return `${p.key}: boolean, default ${p.default}`
    case 'number':
      return `${p.key}: number ${p.min}..${p.max}, default ${p.default}`
    case 'choice':
      return `${p.key}: ${p.options.map((o) => `"${o.value}"`).join(' or ')}, default "${p.default}"`
    default:
      return `${p.key}: text, default "${p.default}"`
  }
}

function symbolRow(def: SymbolDef): string[] {
  const g = geometry(def.id, def.size.w, def.size.h)
  const cavities = (g.cavities ?? []).map((c) => (g.scale?.cavity === c.id ? `${c.id} (scale ${g.scale.v0}..${g.scale.v1} ${g.scale.unit})` : c.id))
  const notes = [def.autoLabel === false ? 'no automatic label' : '', labelText(def) !== def.name.toLowerCase() ? `label "${labelText(def)}"` : '']
  return [
    `\`${def.id}\``,
    def.name,
    (def.aliases ?? []).join(', '),
    `${def.size.w} × ${def.size.h}`,
    def.min && def.resize !== 'none' ? `${def.resize}, min ${def.min.w} × ${def.min.h}` : def.resize,
    (def.params ?? []).map(paramText).join('; '),
    cavities.join('; '),
    (g.anchors ?? []).map((a) => `${a.id} (${a.kind})`).join(', '),
    notes.filter(Boolean).join('; '),
  ]
}

function symbolsMd(): string {
  const later = json<{ later: Row[] }>('catalogue.json').later
  const out: string[] = [
    HEADER('the symbol code in src/symbols and spec/catalogue.json'),
    '# Symbols',
    '',
    `${SYMBOLS.length} symbols in ${PACKS.length} packs. A recipe names one in \`"symbol"\` by its id. \`npm run render -- --symbol <id>\` shows one symbol in full, with the position and direction of each anchor.`,
    '',
    '- size: the default width × height in world units (1 unit is 1 pixel at 100 %). resize: `free` (w and h), `uniform` (w or h: the shape stays), `width`, `height` or `none`.',
    '- parameters: set them in `"params"`. A choice is a string; `"capacity": 50` is read as "50".',
    '- cavities: the keys of `"contents"`. A cavity with a scale also takes `"reading"`, when the symbol stands upright.',
    '- anchors: id (kind). A recipe names an anchor by its id, or by its kind when only one anchor of the symbol has that kind.',
    '',
    'Anchors that fit each other: `base` stands on `surface`; `mouth` takes `plug` (and the `tip` of a tube or a jet); `round` sits in `cup`; `neck` is gripped by `grip`; `rod` carries `sleeve`; `port` and `terminal` take the ends of tubes and wires; `heat` is the top of a flame.',
  ]
  for (const pack of PACKS) {
    const defs = SYMBOLS.filter((d) => d.pack === pack.id).sort((a, b) => a.id.localeCompare(b.id))
    out.push('', `## ${pack.name}`, '')
    out.push(table(['id', 'name', 'aliases', 'size', 'resize', 'parameters', 'cavities', 'anchors', 'notes'], defs.map(symbolRow)))
  }
  out.push(
    '',
    '## Not drawn yet',
    '',
    `These ${later.length} symbols are planned and are not in the editor, so a recipe cannot use them: ${later.map((l) => `${l.name} (${l.pack})`).join(', ')}.`,
  )
  return `${out.join('\n')}\n`
}

function templatesMd(): string {
  const plans = json<{ templates: Plan[] }>('templates.json').templates
  const out: string[] = [
    HEADER('spec/templates.json'),
    '# Templates',
    '',
    `${plans.length} ready-made set-ups. Look here first: if the request is one of these, \`npm run render -- --template <id> --out <dir>\` writes it, and \`--explain\` lists its parts with their anchors. A template is not a recipe: to change one, write a recipe of your own with the same symbols.`,
    '',
    'Each entry gives the id, the title, the practicals it serves, the symbols it uses, and how it is set up.',
  ]
  for (const group of ['General', 'Chemistry', 'Biology', 'Physics']) {
    out.push('', `## ${group}`)
    for (const t of plans.filter((p) => p.group === group)) {
      out.push('', `### ${t.id}: ${t.title}`, '', `- practicals: ${t.refs}`, `- symbols: ${t.uses.map((u) => `\`${u}\``).join(', ')}`, `- set-up: ${t.notes}`)
    }
  }
  return `${out.join('\n')}\n`
}

function presetsMd(): string {
  const row = (p: { name: string; kind: string; colour: string; cloudy?: boolean }): string[] => [
    p.name,
    p.kind + (p.cloudy ? ', cloudy' : ''),
    `\`${p.colour}\``,
  ]
  const out: string[] = [
    HEADER('PRESETS in src/model/contents.ts and RECIPE_PRESETS in src/model/recipe.ts'),
    '# Presets for contents',
    '',
    'A layer of `"contents"` is `{ "preset": "Water", "amount": 0.6 }` or `{ "preset": "Water", "reading": 37 }`. The name is one of these, in any case; the name without its brackets also works when only one preset has it ("Blue" is "Blue (copper sulfate)").',
    '',
    '- `amount` is a fraction of the height of the cavity, 0 to 1. `reading` is a value on the scale of the symbol: the top of that layer goes there.',
    '- A cavity holds at most 4 layers, listed from the bottom. The amounts of the layers that are not a gas add up to 1 or less. At most one layer is a gas, and it is last: it fills what the others leave, so it has no amount. Lumps lie at the bottom: put them first.',
    '- A liquid also takes `"meniscus": true` (on the top liquid only), `"bubbles": "few" | "many"` and `"cloudy": true`. A layer with no preset is `{ "kind": "liquid", "colour": "#cfe8f7", "amount": 0.5 }`, and with nothing but an amount or a reading it is water (a red thread in a thermometer).',
    '',
    table(['preset', 'kind', 'colour'], PRESETS.map(row)),
    '',
    '## Added by the recipe',
    '',
    table(['preset', 'kind', 'colour'], RECIPE_PRESETS.map(row)),
  ]
  return `${out.join('\n')}\n`
}

/** The text of every generated file, by its path inside the skill folder. */
export function skillFiles(): Record<string, string> {
  return { 'reference/symbols.md': symbolsMd(), 'reference/templates.md': templatesMd(), 'reference/presets.md': presetsMd() }
}

function main(): void {
  for (const [name, text] of Object.entries(skillFiles())) {
    const file = join(SKILL_DIR, name)
    mkdirSync(dirname(file), { recursive: true })
    writeFileSync(file, text)
    console.log(`wrote ${file} (${text.split('\n').length - 1} lines, ${text.length} characters)`)
  }
}

// Run it when it is the command, not when a test imports it.
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) main()
