"""Authored v1.1 content: fixes to v1.0 records and full sheets for activities
that shipped without one.  Everything here is merged over activities_v10.json
by build_practicals.py.  Units are written in AQA style (cm3, mol dm-3).
"""

M = "mol dm⁻³"

# ---------------------------------------------------------------------------
# Per-activity overrides.  Keys mirror the record fields used by the builder:
#   title lesson mode time focus change skills equipment safety prep method
#   results questions answers sources expected hazards v11
# 'v11' is the one-line change note that goes into the change log.
# ---------------------------------------------------------------------------
OVERRIDES = {
 1: dict(
   expected="Δm about +0.06 g per 100 cm³ at 20 °C and 101 kPa (n ≈ 0.0042 mol; 44.01 − 28.97 = 15.04 g mol⁻¹ difference). A 0.01 g balance would give only one significant figure in Δm.",
   prep_add="Check that the loaded 100 cm³ syringe is within the capacity of the 0.001 g balance before booking it; many 0.001 g balances are limited to 200–300 g.",
   hazards="Gas bags; no heating; teacher only",
   v11="Added expected Δm, balance-capacity check and consistent units.",
 ),
 2: dict(
   expected="2.000 g of MgSO4·7H2O contains 1.024 g water and leaves 0.977 g MgSO4; x = 7.0 if dehydration is complete. A residue that stops losing mass early gives x below 7.",
   hazards="Hot crucible; spitting on first heating",
 ),
 3: dict(
   expected="0.200 g Mg (0.00823 mol) gains about 0.132 g oxygen if fully converted; a 0.001 g balance therefore resolves the gain to better than 1%.",
   hazards="Burning Mg (do not stare); hot crucible",
 ),
 4: dict(
   prep="Use standardised NaOH and disclose its measured concentration. Supply enough acid for three accurate titres plus a rough run. Pilot the endpoint and confirm the expected titre range: about 16.5 cm³ for 2.2 g and 20.5 cm³ for 1.8 g of succinic acid with 0.1000 mol dm⁻³ NaOH.",
   expected="Titre = 0.00125 × 250 × 118.09 / (mass in g × 25.0) cm³ per 25.0 cm³ of 0.1000 mol dm⁻³ NaOH; 2.000 g gives 18.45 cm³.",
   hazards="Dilute acid and alkali",
   v11="Corrected the expected titre range (v1.0 said 17–21 cm³; 2.2 g gives 16.8 cm³).",
 ),
 5: dict(
   expected="34.01 cm³ of 0.07350 mol dm⁻³ KHP per 25.0 cm³ of exactly 0.1000 mol dm⁻³ NaOH; individual repeats should agree within 0.10 cm³.",
   hazards="Dilute alkali",
 ),
 6: dict(
   expected="A 5.0% (w/v) vinegar gives a mean titre of about 30 cm³ of diluted vinegar per 25.0 cm³ of 0.1000 mol dm⁻³ NaOH.",
   hazards="Dilute acid and alkali",
 ),
 7: dict(
   prep_add="The 9 cm³ titre carries about ±1% burette uncertainty. If a larger titre is preferred, standardise 0.0500 mol dm⁻³ NaOH instead (expected titre about 18 cm³) and change both sheets together.",
   expected="0.800 g CaCO3 (0.00799 mol) consumes 0.01599 mol HCl of the 0.02500 mol added; the 0.00901 mol excess gives 0.000901 mol per 25.0 cm³ aliquot, i.e. 9.01 cm³ of 0.1000 mol dm⁻³ NaOH.",
   hazards="Dilute acid; effervescence; gentle heating",
   v11="Added the titre-size note and the worked expected result.",
 ),
 8: dict(
   expected="25.0 cm³ of 0.400 mol dm⁻³ NaOH needs 25.0 cm³ of 0.400 mol dm⁻³ HCl and gives at most 0.584 g NaCl. NaCl solubility is about 36 g per 100 g water, so the 50 cm³ mixture must be reduced to under about 2 cm³ before crystals appear.",
   hazards="Warm evaporating basin; dilute acid and alkali",
 ),
 9: dict(
   expected="2.000 g NaHCO3 leaves 1.262 g Na2CO3; total loss 0.738 g (0.524 g CO2 and 0.214 g H2O).",
   hazards="Hot crucible",
 ),
 10: dict(
   results="Lead solution / cm³ versus model PbI2 mass / g (simulated data with realistic scatter): 0.50, 0.228; 1.00, 0.466; 1.50, 0.688; 2.00, 0.927; 2.50, 1.149; 3.00, 1.158; 3.50, 1.151; 4.00, 1.155.",
   answers=[
     ("What is the breakpoint and ratio?", "The rising line and the plateau intersect at 2.50 cm³ of 1.00 mol dm⁻³ Pb(NO3)2, i.e. 0.00250 mol Pb²⁺ against 0.00500 mol I⁻: Pb:I = 1:2. Individual points scatter by about ±0.01 g, so the intersection of the two fitted lines, not the largest point, locates the breakpoint."),
     ("Write the equation.", "Pb²⁺(aq) + 2I⁻(aq) → PbI2(s)."),
     ("Why would precipitate height be less reliable than dry mass?", "Height depends on settling, particle size and packing; a common total volume does not control all of these."),
   ],
   expected="Plateau mass = 0.00250 mol × 461.0 g mol⁻¹ = 1.153 g; the model points are scattered by about ±1% around the ideal lines.",
   hazards="Data exercise; no reagents",
   v11="Model dataset now carries realistic scatter so the 'fit two lines, do not pick the largest point' instruction is meaningful.",
 ),
 11: dict(hazards="Low-voltage tester; sulfur away from flames; quartz dust"),
 12: dict(
   equipment="Water burette or narrow tap stream; receiving beaker; dry plastic rod and cloth; molecular models of H2O, CO2 and CH4.",
   safety="Use water only. Secure glassware and keep the stream away from electrical equipment. Dry spills promptly.",
   method=[
     "Predict from molecular shape whether H2O, CO2 and CH4 have a net dipole. Record each prediction with a diagram before the demonstration.",
     "Teacher: open the burette tap to give a thin, steady stream of water into a beaker. Charge a plastic rod by rubbing with a dry cloth and bring it close to, but not touching, the stream. Record the deflection.",
     "Repeat with the rod charged more and less strongly, and with a rod discharged by touching it to an earthed metal object as a control.",
     "Read the reference note: a charged rod also deflects streams of non-polar liquids such as hexane, less strongly, because any liquid is polarised by an electric field and tap water also contains ions. The deflection shows the water is attracted by the field; on its own it does not prove a permanent molecular dipole.",
     "Use the models to explain why H2O has a net dipole while CO2 and CH4 do not, in terms of bond polarity and shape.",
     "State what the demonstration establishes and what it does not, and name other evidence (for example the high relative permittivity and boiling point of water) that supports the polar model.",
   ],
   results="Molecule; shape; bond polarity; predicted net dipole; observation (water only); what the observation does and does not establish.",
   questions=["Why is CO2 non-polar despite polar bonds?", "Why does H2O have a net dipole?", "What does the demo not establish?"],
   answers=[
     ("Why is CO2 non-polar despite polar bonds?", "The two equal C=O bond dipoles oppose and cancel in the linear molecule."),
     ("Why does H2O have a net dipole?", "Its bent geometry prevents cancellation of the O–H dipoles."),
     ("What does the demo not establish?", "It does not by itself establish molecular polarity: non-polar liquids are also deflected (less strongly) because the field polarises any liquid, and tap water contains ions. Deflection is consistent with a polar molecule but is not proof of one."),
   ],
   prep="Trial stream thickness and rod charging before class. This water-only activity replaces the six-solvent comparison, which was misleading because non-polar liquids also deflect. Assess the molecular reasoning rather than the size of the stream movement.",
   hazards="Water near electrical equipment; none chemical",
   v11="Student and teacher sheets written (absent from v1.0). The sheet now states explicitly that the deflection is not proof of polarity.",
 ),
 13: dict(hazards="Reference observations only; no student reagents"),
 14: dict(hazards="Barium salts toxic; collect waste"),
 15: dict(
   expected="AgCl white, dissolves in 2 mol dm⁻³ NH3; AgBr cream, dissolves only in concentrated NH3; AgI yellow, insoluble in both.",
   hazards="Silver nitrate stains; teacher-only concentrated ammonia",
 ),
 16: dict(
   equipment="Fresh nominally 0.100 mol dm⁻³ ammonium iron(II) sulfate in dilute H2SO4; standardised 0.0200 mol dm⁻³ KMnO4; 25.0 cm³ pipette; burette; 1.0 mol dm⁻³ H2SO4, 20 cm³ per run.",
   expected="25.0 cm³ of 0.100 mol dm⁻³ Fe²⁺ needs 0.000500 mol MnO4⁻ = 25.00 cm³ of 0.0200 mol dm⁻³ KMnO4; scale to the standardised concentration.",
   hazards="Permanganate oxidiser and stains; dilute sulfuric acid",
   v11="Removed the contradictory 'approximately 0.1000' concentration wording.",
 ),
 17: dict(
   title="Enthalpy of combustion of alcohols by calorimetry",
   mode="Student practical", time="50–60 min",
   focus="Measure an enthalpy of combustion, quantify how far heat loss depresses the result and compare alcohols per mole.",
   change="Restores a controlled spirit-burner calorimetry (fixed water mass, fixed temperature rise, draught shield, explicit heat-loss evaluation). v1.0 had replaced this entry with a verbatim copy of entry 18 and the promised written combustion comparison was absent.",
   skills="Spirit burner and calorimeter set-up; fuel mass loss; q = mcΔT; ΔH per mole; heat-loss evaluation; homologous-series comparison.",
   equipment="Spirit burners with caps, one alcohol each (methanol, ethanol, propan-1-ol, butan-1-ol); copper calorimeter or 250 cm³ conical flask; clamp and stand; draught shield; 0.1 °C thermometer or probe; 100 cm³ measuring cylinder; 0.01 g balance; heatproof mat.",
   safety="Wear goggles. Alcohols are flammable: keep burners capped except when in use, never refill or move a lit burner, and keep stock bottles away from flames. Tie back hair and stand while heating. Extinguish by replacing the cap, not by blowing. Methanol is toxic by inhalation and skin contact: use a ventilated room and gloves for spills.",
   method=[
     "Measure 100 cm³ (100 g) of water into the calorimeter and clamp it so its base is about 2 cm above the burner wick, inside the draught shield. Record the initial water temperature to 0.1 °C.",
     "Weigh the capped burner containing the first alcohol. Remove the cap, place the burner under the calorimeter, light it and stir the water gently.",
     "Heat until the water temperature has risen by about 20 °C, replace the cap to extinguish the flame and immediately record the maximum temperature reached.",
     "Reweigh the capped burner. Record the mass of alcohol burned.",
     "Replace the water with a fresh 100 cm³ portion and repeat for each alcohol under identical conditions (same distance, shield and temperature rise). Repeat one alcohol to estimate repeatability.",
     "Calculate q = 100 × 4.18 × ΔT (J), n = mass burned / Mr, and ΔHc = −q/n in kJ mol⁻¹. Compare with data-book values and calculate the percentage of the expected energy that reached the water.",
   ],
   results="Alcohol; Mr; burner mass before and after / g; mass burned / g; initial and maximum water temperature / °C; ΔT / °C; q / J; n / mol; ΔHc / kJ mol⁻¹; data-book ΔHc; percentage captured.",
   questions=["Why are measured values much less exothermic than data-book values?", "Why compare alcohols per mole rather than per gram?", "How does using the same temperature rise for every alcohol improve the comparison?"],
   answers=[
     ("Why are measured values much less exothermic than data-book values?", "Heat is lost to the surroundings and the calorimeter, combustion is incomplete (soot shows carbon forming) and alcohol evaporates from the wick without burning; every effect makes the measured magnitude too small, typically 30–60% of the data-book value."),
     ("Why compare alcohols per mole rather than per gram?", "The pattern in the homologous series comes from the bonds broken and formed per molecule: each extra CH2 adds roughly 650 kJ mol⁻¹. Data-book ΔHc: methanol −726, ethanol −1367, propan-1-ol −2021, butan-1-ol −2676 kJ mol⁻¹."),
     ("How does using the same temperature rise for every alcohol improve the comparison?", "Heat loss depends on the temperature difference from the room and on the heating time; a fixed rise makes the loss similar for every alcohol, so the comparison is fairer even though each absolute value is too small."),
   ],
   prep="Fill burners to the same level and check that wicks give a steady flame. Pilot the burner-to-calorimeter distance so a 20 °C rise takes 2–4 min (about 0.5–1.0 g of alcohol). Expect 30–60% of the data-book magnitude with a clear rising trend along the series. Give data-book values only after students have calculated. Cap burners immediately after use and store them away from flames.",
   expected="With 100 g water and ΔT = 20 °C, q = 8360 J; ethanol (Mr 46.07) burning about 0.6 g would give roughly −640 kJ mol⁻¹ against the data-book −1367 kJ mol⁻¹.",
   sources=["https://media.aqa.org.uk/resources/chemistry/AQA-7404-7405-PHBK.PDF"],
   hazards="Open flames; flammable alcohols; methanol toxic",
   v11="Rewritten as a genuine combustion calorimetry practical; v1.0 sheet was a duplicate of 18. This reverses a v1.0 decision and should be confirmed by the department.",
 ),
 18: dict(
   expected="0.0250 mol water formed; with ΔH ≈ −57 kJ mol⁻¹, q ≈ 1.43 kJ and ΔT ≈ +6.8 °C for 50 g of solution.",
   hazards="1 mol dm⁻³ acid and alkali",
 ),
 19: dict(
   equipment="NaHCO3 about 3.50 g; anhydrous Na2CO3 about 2.50 g; two 30.0 cm³ portions of 2.00 mol dm⁻³ HCl; large supported insulated cup with loose lid; temperature probe; timer; balance.",
   safety="Wear goggles. Add solids in a controlled way to prevent foam overflow. The cup must have ample headspace and must not be sealed. Use matched separate runs, not a combined reaction.",
   method=[
     "Measure 30.0 cm³ of 2.00 mol dm⁻³ HCl into the insulated cup. Record the temperature every 30 s for 2 min to establish a baseline.",
     "Weigh about 3.50 g of NaHCO3 accurately. At 2 min add it in three or four portions over about 30 s, stirring, so that foam stays inside the cup. Keep the lid loose.",
     "Continue recording every 30 s for 5 min after the addition. Weigh the cup and contents afterwards to obtain the solution mass.",
     "Rinse and dry the cup. Repeat steps 1–3 with a fresh 30.0 cm³ of acid and about 2.50 g of anhydrous Na2CO3.",
     "Plot each run and extrapolate the post-addition trend back to the addition time to obtain a corrected ΔT. Calculate q = m × 4.18 × ΔT and ΔH per mole of solid for each reaction (ΔH1 for NaHCO3, ΔH2 for Na2CO3). A temperature fall means ΔH is positive.",
     "Construct the Hess cycle for 2NaHCO3(s) → Na2CO3(s) + CO2(g) + H2O(l) and calculate ΔH = 2ΔH1 − ΔH2. Compare with the reference value and account for the difference.",
   ],
   results="Reaction; acid volume; solid mass / g; moles; temperature–time readings; corrected ΔT / °C; solution mass / g; q / J; ΔH / kJ mol⁻¹; Hess-cycle result.",
   questions=["Why multiply the hydrogencarbonate value by two?", "Why subtract the carbonate value?", "Why might the result differ from a reference?"],
   prep="Trial these specified masses with the selected cup. HCl is 0.0600 mol; the solids require about 0.0417 mol and 0.0472 mol respectively, so acid is in excess in both runs. Allow extra acid and solid for repeats. If overflow occurs, scale both solid and acid together only after a technician trial.",
   expected="Expect the NaHCO3 run to cool by about 5–8 °C (ΔH1 ≈ +20 to +30 kJ mol⁻¹) and the Na2CO3 run to warm by about 4–5 °C (ΔH2 ≈ −26 to −30 kJ mol⁻¹), giving ΔH(decomposition) of roughly +60 to +90 kJ mol⁻¹. The value from standard enthalpies of formation is about +92 kJ mol⁻¹.",
   hazards="2 mol dm⁻³ HCl; foaming",
   v11="Student and teacher sheets written (absent from v1.0); expected magnitudes added.",
 ),
 20: dict(
   equipment="Verified anhydrous MgSO4 about 3.01 g; MgSO4·7H2O about 6.16 g; deionised water; 0.001 g balance; insulated cup with loose lid; sensitive temperature probe; timer.",
   safety="Wear goggles. Keep the anhydrous reagent closed before weighing. Use separate clean dry cups or runs; do not heat the mixtures.",
   method=[
     "Weigh 50.00 g of deionised water into the insulated cup on the balance. Record the temperature every 30 s for 2 min.",
     "Weigh about 3.01 g of anhydrous MgSO4 (0.0250 mol) accurately. At 2 min add it all at once, replace the loose lid and stir continuously; record every 30 s for 6 min or until the reading has clearly passed its maximum.",
     "Rinse and dry the cup. Weigh 46.85 g of water into it: this plus the 3.15 g of crystal water in the hydrate gives 50.0 g of water in the final solution. Record the baseline as before.",
     "Weigh about 6.16 g of MgSO4·7H2O (0.0250 mol) accurately, add it at 2 min, stir and record for 6 min. The change is small, so read to 0.1 °C or better.",
     "Extrapolate both traces to the addition time to obtain corrected ΔT values. Calculate q = m(solution) × 4.18 × ΔT and ΔH per mole for each dissolution, keeping the sign convention.",
     "Both runs end as the same solution, so for MgSO4(s) + 7H2O(l) → MgSO4·7H2O(s), ΔH(hydration) = ΔH(anhydrous) − ΔH(hydrate). Compare with the reference value and comment on the relative uncertainty of the small hydrate signal.",
   ],
   results="Run; water mass / g; salt mass / g; moles; readings; corrected ΔT / °C; q / J; ΔH / kJ mol⁻¹; ΔH(hydration).",
   questions=["Why reduce added water in the hydrate run?", "What hydration is measured?", "What if the hydrate signal is indistinguishable from noise?"],
   prep="For exactly 0.0250 mol use 3.009 g anhydrous salt, 6.162 g hydrate and 46.85 g added water in the hydrate run. Anhydrous MgSO4 dissolves slowly and cakes: use fine powder from a freshly opened or oven-dried stock and stir continuously. Pilot the small hydrate temperature signal and record sensitivity and repeatability.",
   expected="Anhydrous run: about +8 to +11 °C (ΔH ≈ −85 to −95 kJ mol⁻¹; reference about −91). Hydrate run: about −1 to −2 °C (ΔH ≈ +15 to +20 kJ mol⁻¹; reference about +16). Reference ΔH(hydration) about −105 kJ mol⁻¹.",
   hazards="None significant; anhydrous salt is hygroscopic",
   v11="Student and teacher sheets written (absent from v1.0); expected magnitudes added.",
 ),
 21: dict(hazards="Iron(III) and thiocyanate solutions; collect waste"),
 22: dict(hazards="Concentrated HCl in mixture; cobalt salts; teacher only in fume cupboard"),
 23: dict(hazards="Concentrated HCl in mixture; cobalt salts; teacher only in fume cupboard"),
 24: dict(
   expected="A 3.00 cm³ aliquot of the 15 cm³ batch contains about 0.003 mol HCl and, with Kc ≈ 4, about 0.007 mol unreacted ethanoic acid, so about 20 cm³ of 0.5000 mol dm⁻³ NaOH; Kc of order 3–5 at room temperature.",
   hazards="Flammable acidic mixture; technician-prepared",
 ),
 25: dict(
   equipment="Molecular model kits; periodic table; drawing paper.",
   safety="Do not place model pieces in the mouth. Count atoms before deciding that two structures are isomers.",
   method=[
     "Build butane, C4H10. Rotate around the single bonds and bend the chain: record that all these arrangements are the same compound because the connectivity is unchanged.",
     "Rebuild the same atoms as 2-methylpropane and confirm that the connectivity is different. Name both isomers and draw each as displayed, structural and skeletal formulae.",
     "Systematically build the three isomers of C5H12 (pentane, 2-methylbutane and 2,2-dimethylpropane). Show that '2-ethylpropane' and '3-methylbutane' are not new isomers.",
     "Build the three C3H8O isomers: propan-1-ol, propan-2-ol and methoxyethane. Count atoms to check that each has the same molecular formula; note that cyclohexane (C6H12) cannot belong in this group.",
     "Extension: build and name the four C4H10O alcohols, then the three C4H10O ethers.",
     "For each set, state the rule you used to decide whether two models are the same compound or isomers.",
   ],
   results="Molecular formula; number of isomers found; names; displayed and skeletal formulae; how sameness was checked.",
   questions=["C4H10 isomers?", "Four C4H10O alcohols?", "Three ethers and the cyclohexane error?"],
   hazards="Models only",
   v11="Student and teacher sheets written (absent from v1.0).",
 ),
 26: dict(
   method="COPY:47",
   results="Sample/control; before mixing; aqueous layer; organic layer; conclusion and limitation.",
   hazards="Bromine water; volatile organics; ventilation",
   v11="Student and teacher sheets written (absent from v1.0); method identical to entry 47 by design.",
 ),
 27: dict(
   equipment="Hard-glass boiling tube; about 2 cm³ liquid paraffin on mineral wool; porous pot or aluminium oxide catalyst; secure clamp; delivery tube with tested anti-suck-back valve; trough; two collection tubes with bungs; pale bromine water; safety screen.",
   safety="Teacher-only with an assistant under a current cracking procedure. Hot glass, flammable gases and suck-back are the main risks. Use a safety screen, eye protection and ventilation. Never ignite the initial air/gas mixture.",
   method=[
     "Teacher: place mineral wool soaked with about 2 cm³ of liquid paraffin at the closed end of the boiling tube and broken porous pot (or aluminium oxide) halfway along. Clamp the tube almost horizontally with the delivery tube dipping into the trough.",
     "Heat the catalyst strongly, then warm the paraffin gently so that vapour passes over the hot catalyst. Allow the first tube of gas (mostly displaced air) to escape and discard it.",
     "Collect the second and third tubes of gas over water and bung them under water. Record all observations at the catalyst and in the trough.",
     "Before heating stops, lift the delivery tube out of the water (or open the valve) so that cooling gas cannot draw water back into the hot tube.",
     "Test one collected tube by adding a few drops of bromine water and shaking with the bung in place; treat a tube of air the same way as a control. Record the colour change.",
     "Explain the observations: write a possible equation for cracking a C10 alkane into a shorter alkane and an alkene, and state what the bromine result shows about the product.",
   ],
   results="Stage; observation; inference; bromine-water result for product gas and for the air control; equation.",
   questions=["Why discard initial gas?", "Example equation?", "Why remove the outlet from water before stopping heating?"],
   sources=["RSC Education: Cracking hydrocarbons (teacher demonstration), edu.rsc.org"],
   hazards="Hot glass; flammable gas; suck-back; teacher only",
   v11="Student and teacher sheets written (absent from v1.0).",
 ),
 28: dict(method="COPY:27", equipment="COPY:27", safety="COPY:27", results="COPY:27", sources="COPY:27",
          hazards="Hot glass; flammable gas; suck-back; teacher only",
          v11="Student and teacher sheets written (absent from v1.0); identical to entry 27 by design."),
 29: dict(hazards="Models and commercial samples only"),
 30: dict(
   results="Compound; bath temperature; time to first persistent cloudiness / s (two runs); observation limit; 1/t; ranking; blank result.",
   hazards="Volatile halogenoalkanes; silver nitrate; 50 °C bath",
   v11="Corrected the garbled results heading ('time 1/2 / s').",
 ),
 31: dict(hazards="Concentrated phosphoric acid; flammable cyclohexene; fume cupboard", expected="10.0 cm³ cyclohexanol (about 9.6 g, 0.096 mol) gives a theoretical 7.9 g cyclohexene; typical isolated yields are 40–70%."),
 32: dict(hazards="Ethanol vapour; no flames; airlock", expected="5.00 g glucose gives at most 2.56 g ethanol; a 50 cm³ culture is about 5% ethanol by mass at best."),
 33: dict(
   prep_add="Sodium dichromate(VI) is a category 1B carcinogen and reproductive toxin; confirm that the department's current CLEAPSS guidance permits its use and prefer potassium dichromate(VI) where its lower solubility (about 13 g per 100 cm³ at 20 °C) still allows an equivalent reagent. The Pearson recipe is quoted from the linked worksheet and has not been verified here.",
   hazards="Cr(VI) carcinogen; hot acidic oxidant; fume cupboard",
   v11="Added the sodium versus potassium dichromate note and marked the recipe as unverified.",
 ),
 34: dict(hazards="Reference observations only"),
 35: dict(hazards="Concentrated phosphoric acid; flammable cyclohexene; fume cupboard", expected="10.0 cm³ cyclohexanol (about 9.6 g, 0.096 mol) gives a theoretical 7.9 g cyclohexene; typical isolated yields are 40–70%."),
 36: dict(
   equipment="Per run: 25.0 cm³ 0.25 mol dm⁻³ H2SO4; 1.0 cm³ fresh 1% starch; 5.0 cm³ 0.0100 mol dm⁻³ Na2S2O3; 10.0 cm³ fresh 0.100 mol dm⁻³ H2O2; 0.0200 mol dm⁻³ KI (25.0, 20.0, 15.0, 10.0 and 5.0 cm³) with water to 25.0 cm³; beakers; pipettes or burettes; timer; white tile.",
   method=[
     "Into a 100 cm³ beaker measure 25.0 cm³ of sulfuric acid, 5.0 cm³ of thiosulfate solution, 1.0 cm³ of starch and the KI volume for run 1 (25.0 cm³), then enough water to make the KI plus water total 25.0 cm³. Swirl.",
     "Measure 10.0 cm³ of hydrogen peroxide into a separate small beaker. Add it to the mixture in one movement, start the timer as you pour and swirl once in a consistent way.",
     "Stop the timer at the first appearance of the blue-black colour, viewed against a white tile. Record t to the nearest second.",
     "Repeat for KI volumes 20.0, 15.0, 10.0 and 5.0 cm³ with 5.0, 10.0, 15.0 and 20.0 cm³ of water. Repeat any run whose duplicate differs by more than 10%.",
     "Calculate the iodide concentration in each 66 cm³ mixture and the relative rate 1/t. Plot 1/t against [I⁻] and, separately, log(1/t) against log[I⁻].",
     "Use the plots (a straight line through the origin; the gradient of the log plot) to deduce the apparent order with respect to iodide, and explain why the same amount of iodine forms in every run.",
   ],
   results="Run; KI volume / cm³; water volume / cm³; [I⁻] in mixture / mol dm⁻³; t / s (two runs); mean t; 1/t / s⁻¹; log[I⁻]; log(1/t).",
   questions=["What is held constant?", "Why is 1/t a relative rate?", "What order is expected and what cannot be inferred?"],
   prep_add="Predicted timings from literature rate constants (unverified locally): roughly 80–120 s at 25.0 cm³ KI, rising to several minutes at 5.0 cm³. If the slowest run exceeds about 5 min, double the peroxide concentration for every run and reissue both sheets. Iodide is regenerated by thiosulfate, so [I⁻] is constant during the clock period; the fixed threshold consumes only 2.5% of the peroxide.",
   expected="[I⁻] from 0.00152 to 0.00758 mol dm⁻³; 1/t should be proportional to [I⁻] (log–log gradient close to 1).",
   hazards="Dilute acid; peroxide; iodine vapour",
   v11="Student sheet written (absent from v1.0); five KI conditions now specified.",
 ),
 37: dict(hazards="Commercial kit only; no lead or acid", expected="Q = 0.050 A × t: 3.0, 6.0, 9.0, 12.0 C; recovered 0.020 A × t: 2.4, 4.8, 7.2, 9.6 C; 80% charge recovery throughout the model."),
 38: dict(
   equipment="0.100 mol dm⁻³ ethanoic acid, NaOH, HCl and ammonia; 25.0 cm³ pipette; burette; calibrated pH probe; 100 cm³ beakers; magnetic or manual stirrer; water; pH buffers 4, 7 and 10.",
   safety="Wear goggles; use a pipette filler. Keep the fragile probe clear of the glass and the stirrer. Rinse and blot gently between solutions; no continuous unmeasured acid stream.",
   method=[
     "Calibrate the pH probe with the supplied buffers. Record the room temperature.",
     "Curve A: pipette 25.0 cm³ of 0.100 mol dm⁻³ ethanoic acid into a 100 cm³ beaker, add just enough water to cover the probe bulb (record the volume) and stir gently. Fill the burette with 0.100 mol dm⁻³ NaOH.",
     "Record the initial pH. Add NaOH in 2.0 cm³ portions, recording the burette reading and the stable pH after each. From 20 cm³ use 0.5 cm³ portions and, while the pH is changing quickly, 0.2 cm³ portions; continue to 40 cm³.",
     "Curve B (second lesson): repeat with 25.0 cm³ of 0.100 mol dm⁻³ ammonia in the beaker and 0.100 mol dm⁻³ HCl in the burette.",
     "Plot pH against volume added for each curve. Mark the equivalence point (midpoint of the steep section), the pH at equivalence and, for curve A, the pH at half the equivalence volume (equal to the pKa of ethanoic acid).",
     "Use the curves to choose a suitable indicator for each titration (its range must lie within the steep section) and explain why the region before equivalence in curve A is nearly flat.",
   ],
   results="Curve; burette reading; volume added / cm³; pH; equivalence volume and pH; half-equivalence pH; indicator chosen and reason.",
   questions=["Expected equivalence volumes?", "Why are equivalence pH values different?", "Does adding immersion water change equivalence volume?"],
   expected="Both equivalence points near 25.0 cm³. Curve A: start about pH 2.9, half-equivalence about 4.8, equivalence about 8.7; phenolphthalein suitable. Curve B: start about pH 11.1, equivalence about 5.3; methyl orange suitable.",
   hazards="0.1 mol dm⁻³ acid and alkali; ammonia odour",
   v11="Student and teacher sheets written (absent from v1.0); expected curve values added.",
 ),
 39: dict(hazards="0.1 mol dm⁻³ acids; electrical probe"),
 40: dict(
   equipment="25.0 cm³ 0.0500 mol dm⁻³ anhydrous Na2CO3 solution; 0.1000 mol dm⁻³ HCl; burette and pipette; calibrated pH probe; 100 cm³ beaker; stirrer.",
   method=[
     "Calibrate the pH probe. Pipette 25.0 cm³ of the carbonate solution into a 100 cm³ beaker and add just enough water to cover the probe bulb. Stir gently.",
     "Fill the burette with 0.1000 mol dm⁻³ HCl. Record the initial pH (expect about 11.5).",
     "Add acid in 1.0 cm³ portions, recording volume and stable pH each time. Change to 0.2 cm³ portions when the pH starts to change quickly, near 12.5 cm³ and again near 25 cm³. Continue to about 32 cm³.",
     "Stir continuously during the second stage so that dissolved carbon dioxide can escape, and let readings settle before recording.",
     "Plot pH against volume. Locate both equivalence points from the two steep sections and read their volumes and pH values.",
     "Write the equation for each stage, check that the second equivalence volume is twice the first, and use the curve to choose an indicator for each stage.",
   ],
   results="Volume added / cm³; pH; first and second equivalence volumes and pH; equations; indicator choice for each stage.",
   questions=["First protonation equation?", "Second stage?", "Why does the second endpoint need twice the acid volume?"],
   expected="First equivalence at 12.5 cm³ (pH about 8.3, phenolphthalein); second at 25.0 cm³ (pH about 3.9, methyl orange). Dissolved CO2 makes the second inflection less sharp.",
   hazards="0.1 mol dm⁻³ HCl; CO2 evolution",
   v11="Student sheet written (absent from v1.0).",
 ),
 41: dict(
   equipment="0.10 mol dm⁻³ Cu(NO3)2 and Mg(NO3)2; 0.10 mol dm⁻³ NH3 for limited addition; 2.0 mol dm⁻³ NH3 for excess; small tubes; separate droppers; white background.",
   safety="Wear goggles and work with ventilation. Ammonia is irritating; do not smell it directly. Collect copper-containing waste. Cobalt is omitted from the core student comparison.",
   method=[
     "Place 10 drops (about 0.5 cm³) of copper(II) nitrate solution in a small tube against a white background. Record its colour.",
     "Add 0.10 mol dm⁻³ ammonia one drop at a time, mixing after each, until a precipitate forms. Record its colour and appearance and the number of drops used.",
     "Add 2.0 mol dm⁻³ ammonia dropwise with mixing until no further change is seen, using no more than 2.0 cm³ in total. Record whether the precipitate dissolves and the colour of any solution formed.",
     "Repeat steps 1–3 with magnesium nitrate solution.",
     "Write equations: the hydroxide precipitation for each metal (aqua ion + 2NH3 → hydroxide + 2NH4⁺) and the ligand-exchange equation for copper with excess ammonia.",
     "Explain why the copper precipitate dissolves in excess ammonia but the magnesium precipitate does not, and why 'magnesium forms no complex ion' is an incorrect statement.",
   ],
   results="Metal; initial colour; limited-NH3 observation; excess-NH3 observation; equations; explanation.",
   questions=["Expected copper observations?", "Copper ligand-exchange equation?", "What about magnesium?"],
   hazards="Ammonia irritant; copper waste",
   v11="Student and teacher sheets written (absent from v1.0).",
 ),
 42: dict(
   equipment="Teacher-selected recordings or the included reference colour sequence and electrode-potential data; periodic table; whiteboard. No student vanadium or chromium reagent handling.",
   safety="Use recorded or reference evidence in this improved activity. Any live demonstration requires its own current approved method; never seal a hydrogen-evolving zinc/acid mixture.",
   method=[
     "Study the vanadium reference sequence: acidified ammonium vanadate(V) (yellow) shaken with zinc gives, in order, blue, green and violet solutions. Assign the oxidation state of vanadium in each colour (VO2⁺, VO²⁺, V³⁺, V²⁺).",
     "Write a half-equation for each reduction step and combine the first with Zn → Zn²⁺ + 2e⁻ to give a full ionic equation.",
     "Study the chromium reference sequence: yellow chromate(VI) becomes orange dichromate(VI) on adding acid and returns to yellow with alkali; orange dichromate(VI) with zinc and acid gives green Cr³⁺ and, if air is excluded, blue Cr²⁺, which turns green again in air.",
     "Classify each chromium colour change as redox (oxidation state changes) or acid–base (oxidation state unchanged), giving the oxidation state of chromium in each species.",
     "Explain why the V²⁺ and Cr²⁺ colours are short-lived in an open tube (oxidation by air) and why the reference sequence lists them as conditional.",
     "Use the supplied electrode potentials to justify why zinc reduces vanadium(V) all the way to vanadium(II) but only just reduces Cr³⁺ to Cr²⁺.",
   ],
   results="Species; colour; oxidation state; half-equation; redox or acid–base. Reference E° / V: Zn²⁺/Zn −0.76; VO2⁺/VO²⁺ +1.00; VO²⁺/V³⁺ +0.34; V³⁺/V²⁺ −0.26; Cr2O7²⁻/Cr³⁺ +1.33; Cr³⁺/Cr²⁺ −0.41.",
   questions=["Vanadium oxidation states in order?", "Chromate/dichromate equation?", "Example reduction half-equation?"],
   hazards="Reference observations only",
   v11="Student and teacher sheets written (absent from v1.0); electrode-potential data supplied.",
 ),
 43: dict(
   equipment="Model kits; structure of limonene from the textbook; supplied model polarimetry data; optional verified enantiomer samples for teacher illustration only.",
   safety="No smelling or sample handling is necessary. Any optional sample demonstration follows the current limonene handling procedure and allows students to opt out of smelling.",
   method=[
     "Draw the skeletal formula of limonene, 1-methyl-4-(prop-1-en-2-yl)cyclohex-1-ene, and mark the one carbon bonded to four different groups.",
     "Build a simplified model of that stereocentre with four different coloured atoms, then build its mirror image. Try to superimpose them and record the outcome.",
     "Swap any two groups on one model and test again: record that a single swap interconverts the enantiomers.",
     "Use the supplied model data: sample A rotates plane-polarised light by +12.3°, sample B by −12.3° and a 1:1 mixture by 0.0°, all at the same concentration and path length. Assign A and B as enantiomers and identify the racemic mixture.",
     "Explain why the racemic mixture shows no rotation and why a reading of 0.0° alone does not prove that a sample contains no chiral molecules.",
     "Optional: if sealed reference samples are shown, note that the two enantiomers of limonene are reported to smell different; this is illustrative and not assessed.",
   ],
   results="Stereocentre identified; superimposability result; effect of swapping two groups; model data (A +12.3°, B −12.3°, 1:1 mixture 0.0°); assignments; explanation.",
   questions=["What makes the centre stereogenic?", "Why is the equal mixture optically inactive?", "Does zero rotation prove no chiral molecules?"],
   prep="Label the rotation values as model teaching data: they are scaled from a literature specific rotation of order ±120° for a 0.10 g cm⁻³ solution in a 1 dm tube and are not measured limonene values. Use identical path-length and concentration conditions in the task. Models supply the main evidence, so no reagent purchase is needed.",
   hazards="Models only; optional sealed samples",
   v11="Student and teacher sheets written (absent from v1.0); model polarimetry values supplied.",
 ),
 44: dict(
   equipment="Pentan-1-ol; glacial ethanoic acid; teacher-dispensed concentrated H2SO4; boiling tubes; 50 °C electric water bath; 1.0 mol dm⁻³ Na2CO3; dropping pipettes; thermometer.",
   safety="Wear splash goggles. The teacher dispenses concentrated acid. No flames or direct smelling. Cool before neutralising; add the acidic mixture slowly to carbonate with space for fizzing. Do not stopper during neutralisation.",
   method=[
     "Place 1 cm³ of pentan-1-ol and 1 cm³ of glacial ethanoic acid in a boiling tube. The teacher adds 3 drops of concentrated sulfuric acid. Mix by gentle swirling.",
     "Stand the tube in the 50 °C water bath for the teacher-approved time (about 10 minutes). Prepare a comparison tube containing only the alcohol and ethanoic acid, unheated.",
     "Cool the tube to room temperature. Place 10 cm³ of sodium carbonate solution in a small beaker.",
     "Pour the reaction mixture slowly into the carbonate solution with stirring, letting fizzing subside between additions. Do not stopper.",
     "Record the appearance of any oily layer on the surface and compare with the comparison tube treated in the same way. Do not smell directly; the teacher may waft a small sample if the department procedure allows.",
     "Name the ester, write the equation for its formation and explain the roles of the sulfuric acid and of the carbonate wash.",
   ],
   results="Tube; appearance after heating; after carbonate wash; layer observed; comparison tube; equation and name.",
   questions=["Product and equation?", "Role of sulfuric acid?", "Why carbonate?"],
   hazards="Concentrated H2SO4 (teacher); flammable alcohol; glacial ethanoic acid",
   v11="Student and teacher sheets written (absent from v1.0).",
 ),
 45: dict(
   equipment="6.00 g 2-hydroxybenzoic (salicylic) acid; 10.0 cm³ ethanoic anhydride; 5 drops concentrated H2SO4 teacher-dispensed; 100 cm³ conical flask; 60 °C electric water bath; Büchner or Hirsch filtration; 15 cm³ ethanol; water; ice; balance; melting-point apparatus.",
   safety="Fume-cupboard synthesis with goggles and suitable gloves; no flames. Ethanoic anhydride is corrosive and a lachrymator; the teacher supervises the anhydride/acid addition and the cooled aqueous work-up. Use vacuum-rated filtration glassware. Laboratory aspirin must never be consumed.",
   method=[
     "Weigh 6.00 g of 2-hydroxybenzoic acid into a 100 cm³ conical flask. In the fume cupboard add 10.0 cm³ of ethanoic anhydride, then (teacher) 5 drops of concentrated sulfuric acid. Swirl to mix.",
     "Warm the flask in the 60 °C water bath for 15–20 minutes, swirling occasionally, until the solid has dissolved and the mixture is clear.",
     "Remove from the bath and, still in the fume cupboard, add about 50 cm³ of cold water slowly to hydrolyse the excess anhydride. Cool in an ice bath for 10 minutes, scratching the inside of the flask with a glass rod to start crystallisation.",
     "Filter the crude product by suction, wash with a little ice-cold water and press it dry on the filter. Weigh the crude product when dry (second lesson if needed).",
     "Recrystallise: dissolve the crude solid in the minimum volume of hot ethanol (about 15 cm³), add about 40 cm³ of warm water and allow to cool slowly, then in ice. Filter by suction, wash with a little ice-cold water and dry the crystals by the department routine.",
     "Weigh the dry purified product and calculate the percentage yield. Measure the melting range and compare it with the reference value; assess purity from the sharpness and position of the range.",
   ],
   results="Salicylic acid mass; crude and purified product masses; theoretical yield; percentage yield; melting range; appearance.",
   questions=["Theoretical mass from 6.00 g salicylic acid?", "Why can purification reduce yield but improve quality?", "What would a broad depressed melting range suggest?"],
   prep="Uses the AQA direct salicylic-acid route, not wintergreen hydrolysis. Trial crystallisation and drying with the actual apparatus; control the exothermic anhydride work-up and allow hydrolysis to finish before filtration. Calibrate or check the melting apparatus: reference values for aspirin lie around 135–138 °C depending on source and heating rate, so treat the value as a comparison, not a promised result. Record students' own filtration, recrystallisation and measurement skills.",
   expected="Theoretical 7.83 g; typical purified yields 50–70%; melting range within a few degrees of 135 °C after recrystallisation, broader and lower for the crude product.",
   hazards="Ethanoic anhydride corrosive/lachrymator; concentrated H2SO4; fume cupboard",
   v11="Student and teacher sheets written (absent from v1.0); melting-point reference made consistent.",
 ),
 46: dict(
   equipment="Coded samples from butan-1-ol, propanal, cyclohexene, 0.50 mol dm⁻³ ethanoic acid and propanone; 0.02 mol dm⁻³ bromine water; 1.0 mol dm⁻³ Na2CO3; fresh Fehling's reagent; teacher-prepared acidified 0.10 mol dm⁻³ dichromate test reagent; tubes; 60 °C electric bath.",
   method=[
     "Planning: the five coded liquids are, in some order, a primary alcohol, an aldehyde, an alkene, a carboxylic acid and a ketone. Write a decision tree that assigns all five with the fewest tests.",
     "Carbonate test: add 5 drops of each sample to 1 cm³ of sodium carbonate solution. Effervescence identifies the carboxylic acid.",
     "Fehling's test: add 5 drops of each remaining sample to 2 cm³ of fresh Fehling's solution and warm in the 60 °C bath for 3 minutes. A brick-red precipitate identifies the aldehyde.",
     "Bromine-water test: add 5 drops of each remaining sample to 1 cm³ of bromine water and shake. Rapid loss of the orange colour identifies the alkene (the aldehyde is already excluded).",
     "Oxidation test: add 5 drops of each remaining sample to 1 cm³ of acidified dichromate reagent and warm in the bath for 3 minutes. Orange to green identifies the primary alcohol; the ketone gives no change.",
     "Record every result, including negatives and the water blank, before assigning codes. State which assignments rest on a positive result and which rest only on elimination.",
   ],
   results="Code; carbonate; Fehling's; bromine water; dichromate; blank; assignment; type of evidence (positive or elimination).",
   questions=["Why test aldehyde separately from alcohol oxidation?", "Does ordinary phenol give the carboxylic-acid carbonate fizz test?", "How are all five assigned?"],
   prep_add="Sodium carbonate is raised to 1.0 mol dm⁻³ so that 0.50 mol dm⁻³ ethanoic acid gives visible effervescence; 0.10 mol dm⁻³ gave a weak result on paper.",
   hazards="Cr(VI) test reagent (teacher); bromine water; flammable organics",
   v11="Student sheet written (absent from v1.0); carbonate reagent concentration raised to 1.0 mol dm⁻³.",
 ),
 47: dict(hazards="Bromine water; volatile organics; ventilation"),
}

# Technician-master intro (v1.0 carried the answers-master intro by mistake)
TECH_INTRO = ("This master consolidates materials, controls and preparation notes for the 47 reviewed activities. "
              "Quantities are per run unless stated; multiply by the number of groups plus a technician trial. "
              "The summary table lists mode, time and the main hazard for booking and risk-assessment purposes.")

ANSWERS_INTRO = ("This replacement covers the 47 reviewed activities. Use it with the improved paired sheets, not the original questions. "
                 "Original wider resources remain available separately.")

SHARED = "Activities 22 and 23 share the cobalt temperature demonstration; 27 and 28 share cracking; 31 and 35 share cyclohexene; 26 and 47 share the prepared-bromine test. Entry 17 (combustion) and entry 18 (neutralisation) are now distinct calorimetry practicals. Plan each shared activity once unless deliberate repetition has a new purpose."

# Short activity names used in file names (keep under 30 characters so the
# package fits inside a deep OneDrive path on Windows).
SHORT = {
 1: "CO2 molar mass", 2: "Water of crystallisation", 3: "Magnesium oxide formula", 4: "Diprotic acid Mr",
 5: "Titration precision", 6: "Vinegar titration", 7: "Carbonate back titration", 8: "NaCl by titration",
 9: "NaHCO3 decomposition", 10: "Precipitation ratios", 11: "Structure from properties", 12: "Polarity water stream",
 13: "Period 3 oxides", 14: "Group 2 solubility", 15: "Halide tests", 16: "Iron(II) redox titration",
 17: "Alcohol combustion", 18: "Neutralisation enthalpy", 19: "Hess cycle NaHCO3", 20: "Hess cycle MgSO4",
 21: "Iron thiocyanate equilibrium", 22: "Cobalt equilibrium temp", 23: "Cobalt equilibrium demo", 24: "Ester Kc",
 25: "Structural isomers", 26: "Unsaturation test", 27: "Cracking demo", 28: "Cracking alkene evidence",
 29: "Addition polymerisation", 30: "Halogenoalkane hydrolysis", 31: "Cyclohexene purification", 32: "Fermentation ethanol",
 33: "Ethanol oxidation reflux", 34: "Distillation aldehyde", 35: "Cyclohexene preparation", 36: "Iodine clock",
 37: "Rechargeable cells", 38: "pH curves RP9", 39: "Acid strength conductivity", 40: "Carbonate pH curve",
 41: "Ammonia ligand exchange", 42: "Transition metal ox states", 43: "Chirality optical rotation", 44: "Ester preparation",
 45: "Aspirin synthesis", 46: "Functional group tests", 47: "Bromine water test",
}
assert all(len(v) <= 30 for v in SHORT.values()) and len(SHORT) == 47
