"""Red-team findings on Improved Practicals v1.0 and the action taken in v1.1.
Each entry: (id, severity, area, activities, finding, action)."""

FINDINGS = [
 ("C1", "Critical", "Packaging", "all",
  "The v1.0 zip claims 47 paired sheets and 102 source copies, but ships 5 of 94 activity-resource files and 61 of 102 source copies. 133 of the 199 links in START HERE.html are broken. Thirteen activities (12, 19, 20, 25, 26, 27, 28, 38, 41, 42, 43, 44, 45) have no student or teacher sheet anywhere in the package, and a further eleven (4, 5, 11, 17, 18, 23, 36, 37, 40, 46, 47) have only one of the pair.",
  "The whole package is regenerated from one data set so every link resolves. The 16 sheets that had no method anywhere were written from the v1.0 intended focus, technician notes and answers; each is flagged 'written in v1.1' in the change log and needs the same local trial as the rest."),
 ("C2", "Critical", "Register", "19, 20, 43",
  "The source register maps one student file and one teacher file to both activities 19 and 20 (comma-separated, unlike the semicolon used elsewhere), has no student row at all for 43, and therefore could never have produced a complete canonical set.",
  "Canonical student and teacher files are generated for all 47 activities regardless of the original file inventory. Source copies that stand for two activities now contain both sheets in sequence. Separators normalised to semicolons."),
 ("H1", "High", "Method", "17",
  "Entry 17 was a verbatim duplicate of entry 18 (same neutralisation method, questions and answers) under a different title. The change log promised that alcohol combustion was 'retained as a written evaluation comparison', but no such comparison exists in any sheet. Dropping alcohol combustion entirely removes a standard, low-risk AS practical that the AQA specification (3.1.4) expects students to have met.",
  "Entry 17 rewritten as a controlled spirit-burner combustion calorimetry (fixed water mass, fixed temperature rise, draught shield, heat-loss evaluation). This reverses a v1.0 decision: confirm with the department before issue."),
 ("H2", "High", "Chemistry", "12",
  "The 'deflected water stream' demonstration is presented as evidence of molecular polarity. Any liquid is polarised in an electric field and non-polar liquids (for example hexane) are also deflected, less strongly; tap water also contains ions. Used as written, the activity teaches a misconception.",
  "Sheets written so that the demonstration is an exercise in judging what an observation establishes; the caveat is stated in the method and in the answer to question 3."),
 ("H3", "High", "Conventions", "all",
  "Every sheet uses mL and M. AQA examinations and the practical handbook use cm³ and mol dm⁻³, and students lose marks for M in written answers.",
  "All volumes and concentrations converted to cm³ and mol dm⁻³; mol−1 rendered as mol⁻¹. The conversion is a flag in the generator if the department prefers the old units."),
 ("H4", "High", "Data protection", "register",
  "Source register CSV and JSON carry the author's personal OneDrive path (user name and academy name) in every one of 102 rows, so the package leaks identifying information whenever it is shared.",
  "Source paths are recorded relative to the '06 - KS5 - Chemistry' folder; the root is stated once in README.txt."),
 ("M1", "Medium", "Numbers", "4",
  "Teacher note gives an expected titre range of 17–21 cm³ for 1.8–2.2 g succinic acid; 2.2 g gives 16.8 cm³ and 1.8 g gives 20.5 cm³.",
  "Range corrected to about 16.5–20.5 cm³ and the formula added under expected results."),
 ("M2", "Medium", "Numbers", "16",
  "Iron(II) stock described as 'approximately 0.1000 M', an internal contradiction (four significant figures cannot be approximate).",
  "Reworded as nominally 0.100 mol dm⁻³ with the standardised value to be disclosed."),
 ("M3", "Medium", "Sheet", "30",
  "Results heading contains the garbled item 'time 1/2 / s'.",
  "Heading rewritten: time to first persistent cloudiness (two runs), observation limit, 1/t."),
 ("M4", "Medium", "Data", "10",
  "The 'model' precipitate data are perfectly linear with no scatter, yet step 3 tells students not to 'select the largest noisy point'. The exercise as written cannot teach the fitting skill it names.",
  "Dataset regenerated with about ±1% scatter around the same 1:2 breakpoint; answer explains that the intersection of the two fitted lines locates it."),
 ("M5", "Medium", "Method", "46",
  "Carbonate test uses 0.10 mol dm⁻³ Na2CO3 against 0.50 mol dm⁻³ ethanoic acid; effervescence would be weak and easy to miss.",
  "Na2CO3 raised to 1.0 mol dm⁻³ in student, teacher and technician text."),
 ("M6", "Medium", "Safety", "33",
  "Reagent is sodium dichromate(VI), a category 1B carcinogen and reproductive toxin; the sheet cites a Pearson recipe that could not be checked from this environment (external hosts are blocked).",
  "Technician note added: confirm current CLEAPSS permission, prefer potassium dichromate(VI) where solubility allows; recipe marked unverified."),
 ("M7", "Medium", "Numbers", "45",
  "Melting-point reference stated as 135–136 °C; published values for aspirin range from about 135 to 140 °C depending on source and heating rate.",
  "Reworded as 'around 135–138 °C depending on source', to be treated as a comparison not a target."),
 ("M8", "Medium", "Masters", "technician master",
  "Technician master opens with the answers-master boilerplate ('use it with the improved paired sheets, not the original questions') and has no overview for booking or risk assessment.",
  "Intro rewritten; a summary table (activity, mode, time, main hazard) added at the front."),
 ("M9", "Medium", "Method", "36",
  "The only iodide-clock sheet present (teacher) never states the five iodide conditions, so the 'defined iodide investigation' could not be run.",
  "Student sheet written with five KI volumes (25 to 5 cm³, water to 25 cm³), the 66 cm³ total and the plots required; predicted timings and a pilot rule added for the technician."),
 ("M10", "Medium", "Teacher support", "25 activities",
  "Teacher sheets give answers but no worked expected result, so a teacher cannot tell at a glance whether a class result is plausible.",
  "An 'Expected results' section added to teacher sheets and the technician master wherever a numerical expectation can be stated."),
 ("L1", "Low", "Files", "all docx",
  "Every docx carries python-docx template metadata (created 2013, author 'python-docx').",
  "Title, author, created and modified dates set on every generated file."),
 ("L2", "Low", "Design", "7",
  "The back titration is designed for a 9 cm³ titre, so burette uncertainty is about ±1%.",
  "Note added offering 0.0500 mol dm⁻³ NaOH (titre about 18 cm³) as an alternative if both sheets are changed together."),
 ("L3", "Low", "Equipment", "1",
  "A loaded 100 cm³ glass syringe can exceed the capacity of a 0.001 g balance.",
  "Capacity check added to the technician note."),
 ("L4", "Low", "Duplication", "22/23, 27/28, 31/35, 26/47",
  "Four pairs of entries are deliberate duplicates so that legacy file names still resolve. This is documented but easy to miss on the index page.",
  "Retained by design; the shared pairs are listed in README.txt, the guide and the index page."),
 ("L5", "Low", "README", "package",
  "README claims all 47 pairs and 102 replacements are present, which was not true of the shipped zip.",
  "README rewritten with the actual inventory, which the verifier checks on every build."),
 ("L6", "Low", "External references", "1, 8, 22, 31, 33, 35, 36, 46",
  "Cited RSC, AQA and Pearson URLs could not be reached from this environment, so they are unverified in v1.1 as they were in v1.0.",
  "URLs left as cited; the cracking demonstration reference is given as a title rather than a guessed URL."),
]

DECISIONS = [
 "Entry 17: keep the restored combustion practical, or revert to the v1.0 neutralisation duplicate. The generator holds both; the change log records which is active.",
 "Units: the package now uses cm³ and mol dm⁻³. Set UNITS_AQA = False in build_practicals.py to return to mL and M.",
 "Entry 33: confirm sodium dichromate(VI) is permitted locally, or substitute potassium dichromate(VI).",
 "Entry 7: decide whether to move to 0.0500 mol dm⁻³ NaOH for a larger titre.",
 "Entry 36: the five KI conditions need a pilot; if the slowest run exceeds five minutes, double the peroxide concentration and reissue.",
]
