import { describe, expect, it } from 'vitest'
import { addSymbol, moveItems } from '../model/commands'
import { newDoc } from '../model/types'
import { HISTORY_LIMIT, createEditorStore } from './store'

describe('history', () => {
  it('one commit is one undo step, and redo brings it back', () => {
    const s = createEditorStore()
    const a = addSymbol(s.getState().doc, 'beaker', 0, 0, 'a')
    s.getState().commit(a)
    s.getState().select(['a'])
    expect(s.getState().past.length).toBe(1)
    s.getState().undo()
    expect(s.getState().doc.order).toEqual([])
    expect(s.getState().selection).toEqual([])
    s.getState().redo()
    expect(s.getState().doc).toBe(a)
    s.getState().redo()
    expect(s.getState().doc).toBe(a)
  })
  it('keeps at most 200 steps and drops the oldest', () => {
    const s = createEditorStore()
    for (let i = 0; i < HISTORY_LIMIT + 20; i++) s.getState().commit(addSymbol(s.getState().doc, 'beaker', i, 0, `s${i}`))
    expect(s.getState().past.length).toBe(HISTORY_LIMIT)
    expect(s.getState().past[0].order.length).toBe(20)
  })
  it('merges arrow-key moves that are less than 500 ms apart', () => {
    const s = createEditorStore()
    s.getState().commit(addSymbol(s.getState().doc, 'beaker', 0, 0, 'a'))
    s.getState().commit(moveItems(s.getState().doc, ['a'], 1, 0), 'arrow', 1000)
    s.getState().commit(moveItems(s.getState().doc, ['a'], 1, 0), 'arrow', 1300)
    s.getState().commit(moveItems(s.getState().doc, ['a'], 1, 0), 'arrow', 1900)
    expect(s.getState().past.length).toBe(3)
    s.getState().undo()
    expect((s.getState().doc.items.a as { x: number }).x).toBe(2)
    s.getState().undo()
    expect((s.getState().doc.items.a as { x: number }).x).toBe(0)
  })
  it('a committed doc that is the same object changes nothing', () => {
    const s = createEditorStore()
    s.getState().commit(s.getState().doc)
    expect(s.getState().past.length).toBe(0)
  })
})

describe('gestures', () => {
  it('previews without history and commits one step at the end', () => {
    const s = createEditorStore()
    s.getState().commit(addSymbol(s.getState().doc, 'beaker', 0, 0, 'a'))
    s.getState().beginGesture('move')
    for (let i = 1; i <= 5; i++) s.getState().preview(moveItems(s.getState().gesture!.base, ['a'], i, 0))
    expect(s.getState().past.length).toBe(1)
    s.getState().updateGesture({ marquee: { x0: 0, y0: 0, x1: 1, y1: 1 } })
    expect(s.getState().gesture?.marquee).toBeTruthy()
    s.getState().endGesture()
    expect(s.getState().gesture).toBeNull()
    expect(s.getState().past.length).toBe(2)
    expect((s.getState().doc.items.a as { x: number }).x).toBe(5)
    s.getState().undo()
    expect((s.getState().doc.items.a as { x: number }).x).toBe(0)
  })
  it('a gesture that changed nothing leaves no step, and a cancelled one restores the base', () => {
    const s = createEditorStore()
    s.getState().beginGesture('marquee')
    s.getState().endGesture()
    expect(s.getState().past.length).toBe(0)
    s.getState().beginGesture('move')
    s.getState().preview(addSymbol(s.getState().doc, 'beaker', 0, 0, 'x'))
    s.getState().cancelGesture()
    expect(s.getState().doc.order).toEqual([])
    s.getState().preview(addSymbol(s.getState().doc, 'beaker', 0, 0, 'x'))
    expect(s.getState().doc.order).toEqual([])
  })
})

describe('view and preferences', () => {
  it('clamps the zoom and resets the add offset', () => {
    const s = createEditorStore()
    expect(s.getState().nextAdd()).toBe(0)
    expect(s.getState().nextAdd()).toBe(20)
    s.getState().setView({ zoom: 50 })
    expect(s.getState().view.zoom).toBe(8)
    s.getState().setView({ zoom: 0.01 })
    expect(s.getState().view.zoom).toBe(0.1)
    expect(s.getState().nextAdd()).toBe(0)
    s.getState().setPrefs({ grid: false })
    expect(s.getState().prefs).toMatchObject({ grid: false, snap: true })
    s.getState().replace(newDoc('Other'))
    expect(s.getState().doc.title).toBe('Other')
    s.getState().setCanvas(10, 20)
    expect(s.getState().canvas).toEqual({ w: 10, h: 20 })
    s.getState().setStatus('hi')
    s.getState().setTool('label')
    s.getState().setClipboard([])
    expect(s.getState().status).toBe('hi')
    expect(s.getState().tool).toBe('label')
  })
})
